name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  dist:
    name: Distribution build
    runs-on: ubuntu-latest
    needs: []
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build sdist and wheel; and check products
        run: pipx run hatch run build-check

      - uses: actions/upload-artifact@v4
        with:
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        if:
          github.event_name == 'release' && github.event.action == 'published'
          && github.repository == 'scipp-atlas/CABIN-learn'